language: android

jdk:
  - oraclejdk8

android:
  components:
    - tools
    - build-tools-24.0.3
    - android-25
    - extra-android-m2repository
    - sys-img-armeabi-v7a-android-23

script:
  - ./gradlew clean ":$MODULE:build"

after_success:
  - .buildscript/deploy_snapshot.sh

env:
   matrix:
     - MODULE=lib

notifications:
  email: true

sudo: false

cache:
   directories:
        - $HOME/.gradle